version: "3.9"
services:

  database:
    image: postgres
    container_name: contacts
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: contacts
    ports:
      - "15432:5432"
    volumes:
      - ./database_docker/init.sql:/docker-entrypoint-initdb.d/init.sql

  contacts:
    build: .
    depends_on:
      - database
    ports:
      - "18001:16001"
    environment:
      CREATE_RANDOM_CONTACTS: "true"
      DATASOURCE_URL: jdbc:postgresql://database:5432/contacts
